FROM    debian:latest

RUN     apt-get update; apt-get install -y wget tar > /dev/null && \
        wget http://nodejs.org/dist/v0.10.33/node-v0.10.33-linux-x64.tar.gz > /dev/null && \
        tar --strip-components 1 -xzf node-v* -C /usr/local > /dev/null && \
        node --version && \
        mkdir /bundle; cd /bundle

EXPOSE  8080

CMD ["node", "/bundle/app/app.js"]